# -*- coding: utf-8 -*-
"""EDA_Cyberbullying

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SwqRBg39Q88dw3CS8BZmC5lD_ZM5LWff

# 📊 Eksplorasi & Statistik Dataset Cyberbullying Instagram
**NLP Project — Klasifikasi Cyberbullying Bahasa Indonesia**  
Institut Teknologi Sumatera

---

## 1. Import Library & Load Dataset
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
from collections import Counter
import re
import warnings
warnings.filterwarnings('ignore')

# Style
plt.rcParams['font.family'] = 'DejaVu Sans'
plt.rcParams['figure.dpi'] = 120
sns.set_theme(style='whitegrid', palette='Set2')

# Load dataset
df = pd.read_csv('/content/DATASET CYBERBULLYING INSTAGRAM.csv', encoding='latin-1', sep=';')

# Bersihkan kolom kosong
df = df[['No.', 'Nama Instagram', 'Komentar', 'Kategori', 'Tanggal Posting', 'Nama Akun IG  Artis/Selebgram']]
df.columns = ['No', 'Nama_Instagram', 'Komentar', 'Kategori', 'Tanggal_Posting', 'Akun_Artis']

df.head()

"""## 2. Informasi Umum Dataset"""

print('=' * 55)
print('          INFORMASI UMUM DATASET')
print('=' * 55)
print(f'  Jumlah baris (data)   : {df.shape[0]:,}')
print(f'  Jumlah kolom          : {df.shape[1]}')
print(f'  Kolom                 : {list(df.columns)}')
print('=' * 55)
print()
print('--- Tipe Data ---')
print(df.dtypes)
print()
print('--- Missing Values ---')
print(df.isnull().sum())

# Statistik deskriptif
print('--- Statistik Deskriptif ---')
df.describe(include='all')

df['panjang_char']  = df['Komentar'].astype(str).apply(len)
df['jumlah_kata']   = df['Komentar'].astype(str).apply(lambda x: len(x.split()))

df

print('Rata-rata jumlah kata per komentar berdasarkan Kategori:')
print(df.groupby('Kategori')['jumlah_kata'].mean().round(2))

"""## 3. Distribusi Label (Bullying vs Non-Bullying)"""

label_counts = df['Kategori'].value_counts()
label_pct = df['Kategori'].value_counts(normalize=True) * 100

print('Distribusi Label:')
print('-' * 35)
for label in label_counts.index:
    print(f'  {label:<18}: {label_counts[label]:>4} data  ({label_pct[label]:.1f}%)')
print('-' * 35)
print(f'  Total            : {label_counts.sum():>4} data')

fig, axes = plt.subplots(1, 2, figsize=(12, 5))
colors = ['#E74C3C', '#2ECC71']

# Bar chart
bars = axes[0].bar(label_counts.index, label_counts.values, color=colors, width=0.5, edgecolor='white', linewidth=1.5)
for bar, val in zip(bars, label_counts.values):
    axes[0].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 5,
                 str(val), ha='center', va='bottom', fontweight='bold', fontsize=13)
axes[0].set_title('Distribusi Label Dataset', fontsize=14, fontweight='bold', pad=12)
axes[0].set_xlabel('Kategori', fontsize=12)
axes[0].set_ylabel('Jumlah Data', fontsize=12)
axes[0].set_ylim(0, max(label_counts.values) * 1.15)
axes[0].tick_params(axis='both', labelsize=11)

# Pie chart
wedges, texts, autotexts = axes[1].pie(
    label_counts.values,
    labels=label_counts.index,
    autopct='%1.1f%%',
    colors=colors,
    startangle=90,
    explode=(0.05, 0.05),
    shadow=True
)
for text in texts: text.set_fontsize(12)
for autotext in autotexts: autotext.set_fontsize(12); autotext.set_fontweight('bold')
axes[1].set_title('Proporsi Label Dataset', fontsize=14, fontweight='bold', pad=12)

plt.tight_layout()
plt.savefig('plot_distribusi_label.png', bbox_inches='tight')
plt.show()
print('✅ Plot tersimpan: plot_distribusi_label.png')

"""## 4. Statistik Panjang Teks Komentar"""

# Hitung panjang teks
df['panjang_char']  = df['Komentar'].astype(str).apply(len)
df['jumlah_kata']   = df['Komentar'].astype(str).apply(lambda x: len(x.split()))

print('=== Statistik Panjang Komentar (Karakter) ===')
print(df.groupby('Kategori')['panjang_char'].describe().round(2))
print()
print('=== Statistik Jumlah Kata per Komentar ===')
print(df.groupby('Kategori')['jumlah_kata'].describe().round(2))

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
palette = {'Bullying': '#E74C3C', 'Non-bullying': '#2ECC71'}

# Distribusi panjang karakter
for label, color in palette.items():
    subset = df[df['Kategori'] == label]['panjang_char']
    axes[0].hist(subset, bins=40, alpha=0.7, label=label, color=color, edgecolor='white')
axes[0].set_title('Distribusi Panjang Komentar (Karakter)', fontsize=13, fontweight='bold')
axes[0].set_xlabel('Jumlah Karakter', fontsize=11)
axes[0].set_ylabel('Frekuensi', fontsize=11)
axes[0].legend(fontsize=11)

# Distribusi jumlah kata
for label, color in palette.items():
    subset = df[df['Kategori'] == label]['jumlah_kata']
    axes[1].hist(subset, bins=30, alpha=0.7, label=label, color=color, edgecolor='white')
axes[1].set_title('Distribusi Jumlah Kata per Komentar', fontsize=13, fontweight='bold')
axes[1].set_xlabel('Jumlah Kata', fontsize=11)
axes[1].set_ylabel('Frekuensi', fontsize=11)
axes[1].legend(fontsize=11)

plt.tight_layout()
plt.savefig('plot_panjang_teks.png', bbox_inches='tight')
plt.show()
print('✅ Plot tersimpan: plot_panjang_teks.png')

# Boxplot perbandingan
fig, axes = plt.subplots(1, 2, figsize=(13, 5))

sns.boxplot(data=df, x='Kategori', y='panjang_char', palette=palette, ax=axes[0], width=0.4)
axes[0].set_title('Boxplot Panjang Karakter per Label', fontsize=13, fontweight='bold')
axes[0].set_xlabel('Kategori', fontsize=11)
axes[0].set_ylabel('Jumlah Karakter', fontsize=11)

sns.boxplot(data=df, x='Kategori', y='jumlah_kata', palette=palette, ax=axes[1], width=0.4)
axes[1].set_title('Boxplot Jumlah Kata per Label', fontsize=13, fontweight='bold')
axes[1].set_xlabel('Kategori', fontsize=11)
axes[1].set_ylabel('Jumlah Kata', fontsize=11)

plt.tight_layout()
plt.savefig('plot_boxplot_teks.png', bbox_inches='tight')
plt.show()
print('✅ Plot tersimpan: plot_boxplot_teks.png')

"""## 5. Analisis Akun Artis/Selebgram"""

akun_counts = df['Akun_Artis'].value_counts()
print('Top 10 Akun Artis/Selebgram dengan Komentar Terbanyak:')
print(akun_counts.head(10).to_string())

# Distribusi bullying per artis (top 10)
top_akun = akun_counts.head(10).index
df_top = df[df['Akun_Artis'].isin(top_akun)]

akun_label = df_top.groupby(['Akun_Artis', 'Kategori']).size().unstack(fill_value=0)
akun_label = akun_label.loc[top_akun]  # urutkan sesuai top

fig, ax = plt.subplots(figsize=(13, 6))
akun_label.plot(kind='bar', ax=ax, color=['#E74C3C', '#2ECC71'], edgecolor='white', width=0.7)
ax.set_title('Distribusi Kategori per Akun Artis (Top 10)', fontsize=13, fontweight='bold')
ax.set_xlabel('Akun Artis/Selebgram', fontsize=11)
ax.set_ylabel('Jumlah Komentar', fontsize=11)
ax.legend(title='Kategori', fontsize=10)
ax.tick_params(axis='x', rotation=30, labelsize=10)

plt.tight_layout()
plt.savefig('plot_akun_artis.png', bbox_inches='tight')
plt.show()
print('✅ Plot tersimpan: plot_akun_artis.png')

"""## 6. Analisis Kata yang Sering Muncul"""

# Stopwords sederhana Bahasa Indonesia
stopwords_id = set([
    'yang', 'dan', 'di', 'ini', 'itu', 'dengan', 'untuk', 'dari', 'ada', 'ke',
    'tidak', 'ya', 'aja', 'sih', 'kak', 'aku', 'kamu', 'dia', 'nya', 'juga',
    'tapi', 'kalau', 'jadi', 'bisa', 'mau', 'sudah', 'udah', 'karena', 'yg',
    'dgn', 'klo', 'gak', 'ga', 'nih', 'deh', 'loh', 'dong', 'saja', 'banget',
    'sama', 'mana', 'lebih', 'buat', 'punya', 'gimana', 'atau', 'pada', 'lagi',
    'tau', 'tahu', 'nggak', 'ngga', 'emang', 'kan', 'kalo', 'kok', 'si',
    'nan', 'kak', 'kakak', 'yaa', 'nya', 'mu', 'ku', 'lah', 'pun'
])

def get_words(text_series):
    all_text = ' '.join(text_series.astype(str).str.lower())
    words = re.findall(r'\b[a-z]{3,}\b', all_text)
    return [w for w in words if w not in stopwords_id]

words_bully     = get_words(df[df['Kategori'] == 'Bullying']['Komentar'])
words_nonbully  = get_words(df[df['Kategori'] == 'Non-bullying']['Komentar'])

top_bully    = Counter(words_bully).most_common(15)
top_nonbully = Counter(words_nonbully).most_common(15)

print('Top 15 Kata — Bullying:')
for w, c in top_bully: print(f'  {w:<20} : {c}')
print()
print('Top 15 Kata — Non-Bullying:')
for w, c in top_nonbully: print(f'  {w:<20} : {c}')

fig, axes = plt.subplots(1, 2, figsize=(15, 6))

for ax, data, title, color in [
    (axes[0], top_bully,    'Top 15 Kata — Bullying',     '#E74C3C'),
    (axes[1], top_nonbully, 'Top 15 Kata — Non-Bullying', '#2ECC71')
]:
    words_list  = [w for w, _ in data]
    counts_list = [c for _, c in data]
    bars = ax.barh(words_list[::-1], counts_list[::-1], color=color, alpha=0.85, edgecolor='white')
    for bar, val in zip(bars, counts_list[::-1]):
        ax.text(bar.get_width() + 0.5, bar.get_y() + bar.get_height()/2,
                str(val), va='center', fontsize=9)
    ax.set_title(title, fontsize=13, fontweight='bold')
    ax.set_xlabel('Frekuensi', fontsize=11)
    ax.tick_params(axis='y', labelsize=10)

plt.tight_layout()
plt.savefig('plot_top_kata.png', bbox_inches='tight')
plt.show()
print('✅ Plot tersimpan: plot_top_kata.png')

"""## 7. Deteksi Duplikat & Data Kosong"""

print('=== Pemeriksaan Kualitas Data ===')
print(f'  Baris duplikat         : {df.duplicated().sum()}')
print(f'  Komentar duplikat      : {df["Komentar"].duplicated().sum()}')
print(f'  Komentar kosong (NaN)  : {df["Komentar"].isnull().sum()}')
print(f'  Komentar kosong ("")   : {(df["Komentar"].astype(str).str.strip() == "").sum()}')
print()

# Komentar terpendek & terpanjang
print('--- Komentar Terpendek (3 karakter pertama) ---')
print(df.nsmallest(3, 'panjang_char')[['Komentar', 'Kategori', 'panjang_char']].to_string(index=False))
print()
print('--- Komentar Terpanjang ---')
print(df.nlargest(3, 'panjang_char')[['Komentar', 'Kategori', 'panjang_char']].to_string(index=False))

"""## 8. Ringkasan Statistik Akhir"""

print('=' * 55)
print('       RINGKASAN STATISTIK DATASET')
print('=' * 55)
print(f'  Total data                : {len(df):,}')
print(f'  Jumlah label Bullying     : {label_counts.get("Bullying", 0):,}')
print(f'  Jumlah label Non-Bullying : {label_counts.get("Non-bullying", 0):,}')
print(f'  Rasio kelas               : Seimbang (50:50)')
print()
print(f'  Rata-rata panjang char    : {df["panjang_char"].mean():.1f}')
print(f'  Rata-rata jumlah kata     : {df["jumlah_kata"].mean():.1f}')
print(f'  Maks panjang char         : {df["panjang_char"].max()}')
print(f'  Min panjang char          : {df["panjang_char"].min()}')
print()
print(f'  Jumlah akun artis unik    : {df["Akun_Artis"].nunique()}')
print(f'  Duplikat komentar         : {df["Komentar"].duplicated().sum()}')
print('=' * 55)